# @file    markdown-link-checker.yml
# @brief   GitHub Actions workflow to check the README file for broken links
# @license Please see the file named LICENSE in the repository
# @repo    https://github.com/caltechlibrary/iga
#
# Inspired by https://github.com/saver999/Broken-Links-Checker (2023-11-26).

name: Markdown link tester
run-name: Test for broken links in Markdown files after ${{github.event_name}} action by ${{github.actor}}

on:
  push:
    paths:
      - '*.md'
  pull_request:
    paths:
      - '*.md'
  workflow_dispatch:
    paths:
      - '*.md'

env:
  labels: bug

jobs:
  check-urls:
    name: Check URLs in Markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Test URLs found in links inside Markdown files
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0

      - name: Create a new issue for the broken links
        if: env.lychee_exit_code != 0
        uses: dacbd/create-issue-action@v1
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
