# @file    markdown-link-checker.yml
# @brief   GitHub Actions workflow to check the README file for broken links
# @license Please see the file named LICENSE in the repository
# @repo    https://github.com/caltechlibrary/iga
#
# Inspired by https://github.com/saver999/Broken-Links-Checker (2023-11-26).

name: Test links in Markdown files
run-name: Test for broken links in Markdown files after ${{github.event_name}} action by ${{github.actor}}

on:
  push:
    paths:
      - '*.md'
  pull_request:
    paths:
      - '*.md'
  workflow_dispatch:
    paths:
      - '*.md'

env:
  labels: bug

jobs:
  check-links:
    name: Test link URLs
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      # - name: Restore cache
      #   uses: actions/cache@v3
      #   with:
      #     path: .lycheecache
      #     key: cache-lychee-${{github.sha}}
      #     restore-keys: cache-lychee-

      - name: Test URLs found inside Markdown files
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --no-progress --exclude-mail --exclude-loopback --include-verbatim '*.md'
          debug: true
          format: markdown
          jobSummary: false

      - name: Post-process the output
        if: env.lychee_exit_code != 0
        run: |
          sed -e 's/^## Summary//' \
              -e 's/^|.*//g' \
              -e 's/^## Errors per input//' \
              -e 's/{.*$/|/g' \
              -e 's/^\[Full Github.*//' \
              < lychee/out.md > lychee/report.md

      - name: Create a new issue for the broken links
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: Broken links in Markdown files
          content-filepath: ./lychee/report.md
